name: Build release zip

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git archive --format=zip -o web4.zip HEAD
      - uses: softprops/action-gh-release@v1
        with:
          files: web4.zip
