name: Build release zip

on:
  push:
    tags:
      - 'v*'    # Запускать только при пуше тегов, начинающихся на v (например, v0.1.0)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: zip -r web4.zip .
      - uses: softprops/action-gh-release@v1
        with:
          files: web4.zip
